# Generated by Django 5.0 on 2024-04-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=300)),
                ('Masul', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=300)),
                ('Masul', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Shaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(max_length=300)),
                ('Familyasi', models.CharField(max_length=300)),
                ('Sharfi', models.CharField(max_length=300)),
                ('viloyat', models.CharField(choices=[('Q', 'Qashqadaryo'), ('N', 'Navoiy'), ('B', 'Buxoro'), ('S', 'Samarqand')], max_length=300, verbose_name='viloyat')),
                ('maxallasi', models.TextField()),
                ('JSHSHIR', models.IntegerField()),
                ('Telefon_raqam', models.CharField(max_length=30)),
                ('Biladigan_tili', models.CharField(choices=[('UZ', 'uzbek'), ('RU', 'rus'), ('NE', 'nemis'), ('EN', 'ingliz')], max_length=30, verbose_name='til')),
                ('Til_bilish_darajasi', models.CharField(choices=[('A1', 'A1 daraja'), ('B2', 'B2 daraja'), ('B1', 'B1 daraja'), ('A2', 'A2 daraja'), ('C2', 'C2 daraja'), ('C1', 'C1 daraja')], max_length=30, verbose_name='daraja')),
                ('Holati', models.CharField(choices=[('U', 'Ayni vaqtda oqimoqda'), ('P', 'Sertifikati bor'), ('E', 'Oqub bolgan')], max_length=30, verbose_name='holat')),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maktab')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tuman')),
            ],
        ),
        migrations.AddField(
            model_name='maktab',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tuman'),
        ),
    ]
