# Generated by Django 5.0 on 2024-04-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaxs',
            name='Biladigan_tili',
            field=models.CharField(choices=[('UZBEK', 'uzbek'), ('RUS', 'rus'), ('ENGLISH', 'ingliz'), ('NEMISH', 'nemis')], max_length=30, verbose_name='til'),
        ),
        migrations.AlterField(
            model_name='shaxs',
            name='Holati',
            field=models.CharField(choices=[("Ayni vaqtda o'qimoqda", "Ayni vaqtda o'qimoqda"), ('Sertifikati bor', 'Sertifikati bor'), ("O'qib bo'lgan", "O'qib bo'lgan")], max_length=30, verbose_name='holat'),
        ),
        migrations.AlterField(
            model_name='shaxs',
            name='Til_bilish_darajasi',
            field=models.CharField(choices=[('B2 daraja', 'B2 daraja'), ('A2 daraja', 'A2 daraja'), ('B1 daraja', 'B1 daraja'), ('A1 daraja', 'A1 daraja'), ('C1 daraja', 'C1 daraja'), ('C2 daraja', 'C2 daraja')], max_length=30, verbose_name='daraja'),
        ),
        migrations.AlterField(
            model_name='shaxs',
            name='viloyat',
            field=models.CharField(choices=[('Q', 'Qashqadaryo'), ('B', 'Buxoro'), ('N', 'Navoiy'), ('S', 'Samarqand')], max_length=300, verbose_name='viloyat'),
        ),
    ]
